#TRIGGER A UNA APP DE NOTIFICACION
name: Push on commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MESSAGE: "Tenes un new commit DESPERTA GONZAAAAAAAA!"
